In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [7]:
#Load the data set
df = pd.read_csv(r"C:\Users\kefiw\OneDrive\Desktop\OIBSIPTask1Level1\retail_sales_dataset.csv")

# Data Inspection

In [9]:
df.head(10)

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount
0,1,2023-11-24,CUST001,Male,34,Beauty,3,50,150
1,2,2023-02-27,CUST002,Female,26,Clothing,2,500,1000
2,3,2023-01-13,CUST003,Male,50,Electronics,1,30,30
3,4,2023-05-21,CUST004,Male,37,Clothing,1,500,500
4,5,2023-05-06,CUST005,Male,30,Beauty,2,50,100
5,6,2023-04-25,CUST006,Female,45,Beauty,1,30,30
6,7,2023-03-13,CUST007,Male,46,Clothing,2,25,50
7,8,2023-02-22,CUST008,Male,30,Electronics,4,25,100
8,9,2023-12-13,CUST009,Male,63,Electronics,2,300,600
9,10,2023-10-07,CUST010,Female,52,Clothing,4,50,200

In [11]:
#shape (dimensions of the dataframe)
df.shape

(1000, 9)

In [12]:
#column data types
df.dtypes

Transaction ID       int64
Date                object
Customer ID         object
Gender              object
Age                  int64
Product Category    object
Quantity             int64
Price per Unit       int64
Total Amount         int64
dtype: object

In [13]:
#checking for null values
df.isnull().values.any()

False

# Descriptive Statistics

In [16]:
#Summary statistics of all numerical variables in the data set
df.describe()

       Transaction ID         Age     Quantity  Price per Unit  Total Amount
count     1000.000000  1000.00000  1000.000000     1000.000000   1000.000000
mean       500.500000    41.39200     2.514000      179.890000    456.000000
std        288.819436    13.68143     1.132734      189.681356    559.997632
min          1.000000    18.00000     1.000000       25.000000     25.000000
25%        250.750000    29.00000     1.000000       30.000000     60.000000
50%        500.500000    42.00000     3.000000       50.000000    135.000000
75%        750.250000    53.00000     4.000000      300.000000    900.000000
max       1000.000000    64.00000     4.000000      500.000000   2000.000000

In [22]:
#selecting numerical columns to calculate the median and mode
num_df = df.select_dtypes(include=np.number)

stats = pd.DataFrame({
    'Median': num_df.median(),
    'Mode': num_df.mode().iloc[0]
})
stats.round(2)

                Median  Mode
Transaction ID   500.5   1.0
Age               42.0  43.0
Quantity           3.0   4.0
Price per Unit    50.0  50.0
Total Amount     135.0  50.0